GET http://127.0.0.1:8080/hello
Authorization: Bearer eyJraWQiOiJhcHBJZCIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJ0b2tlbiBjb21wYW55IiwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNzQwMjkyOTkyLCJleHAiOjE3NDAyOTM4OTJ9.fkBR93IaUL6WaBhZ5We2jab7azCgUg66Xb8qDXLWTMg

###

POST http://127.0.0.1:8080/hellpo
Cookie: JSESSIONID=12B483A259609A8E7600D514FB6A8FCF
X-CSRF-TOKEN: F6K9snsTQfwIekk2-Fag9devU0xQwfp_O73GtVFt6lYM4kezIMGK1kx3cp4lHyhQyHuUk-_Jfi5o-MxSDor30DdY2GY92iKB
Authorization: Bearer eyJraWQiOiJhcHBJZCIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJ0b2tlbiBjb21wYW55IiwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNzQwMjkyOTkyLCJleHAiOjE3NDAyOTM4OTJ9.fkBR93IaUL6WaBhZ5We2jab7azCgUg66Xb8qDXLWTMg

###

POST http://127.0.0.1:8080/auth/signup
Content-Type: application/json

{
    "name": "John1",
    "email":"example.tt123@tst.com",
    "password":"1234"
}
###

POST http://127.0.0.1:8080/auth/login
Content-Type: application/json
Cookie: JSESSIONID=12B483A259609A8E7600D514FB6A8FCF
X-CSRF-TOKEN: F6K9snsTQfwIekk2-Fag9devU0xQwfp_O73GtVFt6lYM4kezIMGK1kx3cp4lHyhQyHuUk-_Jfi5o-MxSDor30DdY2GY92iKB

{
    "name": "John",
    "password":"123"
}

###

POST http://127.0.0.1:8080/auth/refresh
Authorization: Bearer eyJraWQiOiJhcHBJZCIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJ0b2tlbiBjb21wYW55IiwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNzQwMTQzMjc2LCJleHAiOjE3NDAxNDQxNzZ9.yBTyeGoO28C13K4Ckc9UKKrCYCp6OXzO_hulhpEdAAs

eyJraWQiOiJhcHBJZCIsImFsZyI6IkhTMjU2In0.eyJzdWIiOiJ0b2tlbiBjb21wYW55IiwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNzQwMTQzMjc2LCJleHAiOjE3NDAzNTkyNzZ9.0J8HTVtqMPy4KGhrLKYY7fYcPkk8nE_hpn_wtHnQyVQ
###
GET http://127.0.0.1:8080/auth/test
//Authorization: 321

